replicaCount: 1

image:
  repository: nginx
  tag: "1.27.2-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"        # e.g. "nginx" o "alb" si usás AWS Load Balancer Controller
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: demo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []              # ejemplo:
                       # - secretName: demo-tls
                       #   hosts:
                       #     - demo.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
